services:
  app:
    build: ./app
    depends_on:
      - api
    ports:
      - "3000:3000"
  api:
    build: ./api
    depends_on:
      - redis
    ports:
      - "8080:8080"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
